[dev v2.6] k8s november patch release
rancher/kontainer-driver-metadata pull request #1000
Opened 2022-11-03 08:12 UTC by vardhaman22

created pr against a custom branch names dev-v2.6-1122-patches (created from dev-v2.6) because OOB releases.
for issue: https://github.com/rancher/rancher/issues/39370

2022-11-09 15:17 UTC, snasovich commented on rke/k8s_rke_system_images.go
> +		"v1.22.16-rancher1-1": {
There probably won't be 1.22, see more info here: https://github.com/rancher/hyperkube/pull/291#issuecomment-1308896775

2022-11-10 18:06 UTC, snasovich commented on rke/k8s_rke_system_images.go
> +		"v1.22.16-rancher1-1": {
Disregard, 1.22.16 actually got released (https://github.com/kubernetes/kubernetes/releases/tag/v1.22.16)

2022-11-14 22:33 UTC, snasovich requested changes
Same issue as https://github.com/rancher/kontainer-driver-metadata/pull/999#discussion_r1022126576

2022-11-15 05:01 UTC, vardhaman22 commented
> Same issue as [#999 (comment)](https://github.com/rancher/kontainer-driver-metadata/pull/999#discussion_r1022126576)

done

2022-11-15 14:50 UTC, snasovich approved these changes
LGTM!

2022-11-15 17:55 UTC, kinarashah approved these changes
- [x] only hyperkube image changes between v1.22.15 and v1.22.16 
- [x] only hyperkube image changes between v1.23.12 and v1.23.14 
- [x] only hyperkube image changes between v1.24.6 and v1.24.8 
- [x] version info and default version updated 
- [x] no service option changes 
- [x] no addon template changes

2022-11-15 17:58 UTC, merged