[WIP] - December 2022 k3s dev-v2.6-1222-patches
rancher/kontainer-driver-metadata pull request #1034
Opened 2022-12-08 02:55 UTC by nikolaishields

2022-12-08 15:44 UTC, rancher-max requested changes
Please update the default at the top of this channels.yaml file to this latest v1.22 version as well, but otherwise LGTM

2022-12-12 18:36 UTC, rancher-max submitted a review, later dismissed

2022-12-12 20:23 UTC, brandond submitted a review, later dismissed

2022-12-13 20:44 UTC, rancher-max commented
https://github.com/rancher/rancher/issues/39887

2022-12-21 00:29 UTC, brandond approved these changes

2022-12-21 16:16 UTC, rancher-max approved these changes

2022-12-21 21:55 UTC, merged