[WIP] December K3S2 Release
rancher/kontainer-driver-metadata pull request #1050
Opened 2023-01-05 17:03 UTC by nikolaishields

2023-01-05 17:11 UTC, rancher-max requested changes
We should remove v1.25 from this. That should be PRed into dev-v2.7 separately

2023-01-05 17:41 UTC, rancher-max reviewed
LGTM - will approve for merge after we release and remove RCs 👍

2023-01-11 22:09 UTC, rancher-max approved these changes

2023-01-11 22:12 UTC, brandond approved these changes

2023-01-11 22:51 UTC, merged