December 2022 r2 dev v2.7
rancher/kontainer-driver-metadata pull request #1052
Opened 2023-01-06 17:49 UTC by briandowns

2023-01-06 17:56 UTC, brandond requested changes

2023-01-06 17:56 UTC, brandond commented on channels-rke2.yaml
> +  - version: v1.24.9-rc1+rke2r2
I think we should replace v1.24.9+rke2r1 with v1.24.9-rc1+rke2r2. R1 never shipped in a Rancher release as far as I know, and we don't want anyone to be able to pick it.

2023-01-06 20:18 UTC, rancher-max reviewed
LGTM - will approve for merging after we release and update to non-RC versions

2023-01-11 03:16 UTC, brandond approved these changes

2023-01-11 16:10 UTC, rancher-max approved these changes

2023-01-11 23:04 UTC, snasovich approved these changes

2023-01-12 17:57 UTC, merged