January 2023 rke2
rancher/kontainer-driver-metadata pull request #1063
Opened 2023-01-19 19:04 UTC by briandowns

2023-01-19 19:11 UTC, rancher-max requested changes

2023-01-19 19:11 UTC, rancher-max commented on channels-rke2.yaml
> +        version: v3.9.3-build2023010901
We should have the harvest CPI/CSI bumps here as well

2023-01-19 21:09 UTC, rancher-max approved these changes

2023-01-19 21:14 UTC, rancher-max requested changes
Ah wait, I approved by accident. This is technically correct, but we need this to have the RC versions first so that QA can validate.

2023-01-19 21:17 UTC, briandowns commented
> Ah wait, I approved by accident. This is technically correct, but we need this to have the RC versions first so that QA can validate.

Wow, thanks. That slipped right by me somehow. Updated.

2023-01-19 21:18 UTC, rancher-max reviewed
Awesome, thank you for the updates! Looks good now and will give final approval after full release 👍

2023-01-20 19:27 UTC, kinarashah commented on channels-rke2.yaml
>      featureVersions: *featureVersions-v1
Not sure how important is this field, but with this change  `featureVersions: *featureVersions-v1` is now missing for `v1.23.15+rke2r1` so need to add it back

2023-01-27 18:36 UTC, rancher-max approved these changes

2023-01-30 21:16 UTC, ShylajaDevadiga approved these changes

2023-01-30 21:17 UTC, merged

2023-02-07 16:28 UTC, cwayne18 commented on data/data.json
> +       "cis-1.6"
@rancher-max shouldnt this be cis-1.23 here?