[dev-v2.6] February RKE2 patches
rancher/kontainer-driver-metadata pull request #1106
Opened 2023-03-08 00:01 UTC by brooksn

2023-03-08 00:04 UTC, rancher-max requested changes
I think the branch is incorrect -- should be `dev-v2.6-0123-patches` unless something changed @snasovich @kinarashah ?

2023-03-08 00:19 UTC, kinarashah commented
@rancher-max  The latest I have on feb patches is 

**Feb patches:**
2.6 target branch: `dev-v2.6-for-2.7.2`
**Todo**: Will create branch and sync changes from `dev-v2.6` to `dev-v2.6-for-2.7.2` after `dev-v2.6` is up to date
2.7 target branch: `dev-v2.7`

I am yet to finish up the todo item and sync branches, we released KDM today so I'll be able to get this done tomorrow.

2023-03-10 23:54 UTC, rancher-max submitted a review, later dismissed
I know in the past we made maxChannelServerVersion 2.6.99, but I like it as 2.7.99 so I'm approving this 😄

2023-03-14 17:35 UTC, snasovich commented on channels-rke2.yaml
> +    maxChannelServerVersion: v2.7.99
We've been doing `maxChannelServerVersion: v2.6.99` for 2.6 releases except of `v1.23.16+rke2r1` and `v1.24.10+rke2r1` where it was accidentally set to `v2.7.99`. I think we want to go back to setting it to `v2.6.99` for consistency.

2023-03-14 17:35 UTC, snasovich commented on channels-rke2.yaml
> +    maxChannelServerVersion: v2.7.99
Same as the other comment regarding `v2.7.99` vs. `v2.6.99`.

2023-03-14 19:06 UTC, rancher-max approved these changes

2023-03-14 21:52 UTC, merged