Add ACI-CNI support for 5.2.3.6
rancher/kontainer-driver-metadata pull request #1120
Opened 2023-04-14 10:22 UTC by LavanyaVaddavalli

2023-04-14 11:24 UTC, LavanyaVaddavalli commented
Testing is in progress for v1.22.17-rancher1-3 and v1.23.16-rancher2-2 versions. Could not test v1.24.13-rancher1-1 as some of the system images like rancher/hyperkube:v1.24.13-rancher1 seems to have not been pushed into docker.io yet.

2023-04-18 00:02 UTC, snasovich requested changes
Added some comments to address/reply to.

Meanwhile, with https://github.com/rancher/kontainer-driver-metadata/pull/1116 now merged let's rebase this PR.

2023-04-18 00:02 UTC, snasovich commented on rke/k8s_rke_system_images.go
> +		"v1.22.17-rancher1-3": {
Is it a requirement to add this for 1.22?
The issue with not having this version also added to 2.7 branch as this may cause issues with upgrading 2.6.x Rancher setups (that will have this version) to 2.7.x setups (that will not have this version as it stands currently).

So we either skip adding this 1.22 version here or update https://github.com/rancher/kontainer-driver-metadata/pull/1110 to also include this `v1.22.17-rancher1-3` version.

2023-04-18 00:02 UTC, snasovich commented on rke/k8s_rke_system_images.go
> +		// Enabled out of band post v2.6.12
So far the plan is to align this KDM release with 2.6.12 actually, so let's change the comment as below,
```suggestion
		// Enabled in v2.6.12
```

2023-04-18 00:02 UTC, snasovich commented on rke/k8s_rke_system_images.go
> +		// Enabled out of band post v2.6.12
So far the plan is to align this KDM release with 2.6.12 actually, so let's change the comment as below,
```suggestion
		// Enabled in v2.6.12
```

2023-04-18 07:52 UTC, LavanyaVaddavalli commented
@snasovich addressed all comments and removed 1.22.17-rancher1-3 version so as to avoid issues during upgrade. Rebased the PR as well.

2023-04-18 15:40 UTC, snasovich approved these changes, later dismissed

2023-04-19 00:32 UTC, kinarashah approved these changes, later dismissed

2023-04-19 15:06 UTC, snasovich commented
@siva-muni , please note that we're bumping versions a bit per https://github.com/rancher/kontainer-driver-metadata/pull/1124 - this PR will need to be rebased again once that one is merged (should be today) and template version ranges changed slightly.

2023-04-20 07:22 UTC, LavanyaVaddavalli commented
> @siva-muni , please note that we're bumping versions a bit per #1124 - this PR will need to be rebased again once that one is merged (should be today) and template version ranges changed slightly.

@snasovich please note that we rebased the PR as per your comment

2023-04-20 18:13 UTC, snasovich approved these changes
LGTM. @kinarashah , please review and merge if it looks good for you.

2023-04-20 19:04 UTC, kinarashah approved these changes

2023-04-20 19:04 UTC, merged