May k3s releases
rancher/kontainer-driver-metadata pull request #1137
Opened 2023-05-19 18:22 UTC by briandowns

2023-05-19 20:30 UTC, rancher-max requested changes
As this will be the first v1.26 release, I believe we want to replace v1.26.4. cc @snasovich @kinarashah to confirm.

Also, for 1.26, I noticed that we have some changed args for `flannel-backend`. I believe we need to update this to include `wireguard-native`.
`   --flannel-backend value                    (networking) backend<=option1=val1,option2=val2> where backend is one of 'none', 'vxlan', 'ipsec' (deprecated), 'host-gw', 'wireguard-native', 'wireguard' (deprecated) (default: "vxlan")`

2023-05-26 16:35 UTC, rancher-max reviewed
LGTM! Will officially approve once we cut releases and remove RC. Thank you!

2023-05-26 23:14 UTC, brandond requested changes

2023-05-26 23:14 UTC, brandond commented on channels.yaml
> +        - wiregaurd-native
```suggestion
        - wireguard-native
```

2023-05-26 23:32 UTC, brandond approved these changes, later dismissed
need to `go generate` again, LGTM otherwise.

2023-05-31 18:26 UTC, rancher-max approved these changes

2023-05-31 18:31 UTC, merged

2023-05-31 18:32 UTC, brandond commented on channels.yaml
> +        - wiregaurd-native
still misspelled