[dev-v2.6-for-v2.7.5] May rke2 patches
rancher/kontainer-driver-metadata pull request #1139
Opened 2023-05-23 22:07 UTC by galal-hussein

2023-05-25 19:19 UTC, rancher-max reviewed
LGTM for rc stage -- will approve after we cut releases and remove -rc

2023-05-25 19:52 UTC, rancher-max requested changes

2023-05-25 19:52 UTC, rancher-max commented on channels-rke2.yaml
> +        version: 1.7.101
sorry this is my fault; I wasn't clear in our DM -- these don't exist in 1.24 so you can remove them!

2023-05-25 22:53 UTC, rancher-max reviewed
LGTM for rc stage -- will approve after releases are cut and RC is removed

2023-06-01 17:34 UTC, rancher-max approved these changes

2023-06-01 18:48 UTC, cwayne18 approved these changes

2023-06-01 18:49 UTC, dereknola approved these changes

2023-06-01 18:50 UTC, merged