Added ACI-CNI 5.2.7.1 templates
rancher/kontainer-driver-metadata pull request #1146
Opened 2023-06-06 15:32 UTC by LavanyaVaddavalli

2023-06-07 07:34 UTC, LavanyaVaddavalli commented
Testing is under progress

2023-06-07 14:23 UTC, snasovich requested changes
Couple comments to address, otherwise LGTM

2023-06-07 14:23 UTC, snasovich commented on pkg/rke/k8s_rke_system_images.go
> +		// Enabled out of band post v2.7.2
Minor update to comment, same for the other introduced versions

```suggestion
		// Enabled with v2.7.5
```

2023-06-07 14:23 UTC, snasovich commented on pkg/rke/templates/templates.go
> +			">=1.25.9-rancher2-2":                      aciv5271,
With this range change for `v1.26.4-rancher2-1`, `aciv5271` template will be used yet images version `5.2.3.6` are referenced in the definition of `v1.26.4-rancher2-1`.
I understand that ACI-CNI is not tested for 1.26, but I think the best option here is to bump versions to 5.2.7.1 for `v1.26.4-rancher2-1` to be consistent. Another rational is it won't make it worse and there is a higher chance of newer version of ACI-CNI plugin working on 1.26.

2023-06-09 11:43 UTC, LavanyaVaddavalli commented
@snasovich Addressed comments in e06af2e5da58f9659b0698a2f320d2acddea1655. Added aci cni version bump to 1.26 k8s version as well

2023-06-14 17:15 UTC, snasovich approved these changes, later dismissed
Approved, but also hinging on RKE1 PR https://github.com/rancher/rke/pull/3258

2023-06-15 14:55 UTC, snasovich approved these changes

2023-06-15 20:57 UTC, kinarashah approved these changes

2023-06-15 21:29 UTC, merged