Rke2june2023update
rancher/kontainer-driver-metadata pull request #1160
Opened 2023-06-19 15:25 UTC by briandowns

2023-07-03 16:39 UTC, galal-hussein submitted a review, later dismissed

2023-07-05 16:43 UTC, rancher-max requested changes
After addressing a couple minor changes, this looks fine from the rke2 perspective. However, I'm not sure why a bunch of other files got added in? Might need a review from @kinarashah or @snasovich to see if there was a change to the 2.6 branch and if these other files are expected now?

2023-07-05 16:43 UTC, rancher-max commented on channels-rke2.yaml
> +    minChannelServerVersion: v2.7.5-alpha1
This should be `v2.6.7-alpha1`

2023-07-05 16:43 UTC, rancher-max commented on channels-rke2.yaml
> +    maxChannelServerVersion: v2.7.99
This should be `v2.6.99`

2023-07-05 18:52 UTC, kinarashah commented
@rancher-max We possibly need a rebase. These changes are already present in the `dev-v2.6-2023-06-patches` branch.

2023-07-05 20:36 UTC, briandowns commented
Rebased.

2023-07-05 20:40 UTC, rancher-max approved these changes

2023-07-05 21:22 UTC, kinarashah approved these changes

2023-07-05 21:22 UTC, merged