Correct etcd and ACI versions
rancher/kontainer-driver-metadata pull request #1171
Opened 2023-06-29 04:55 UTC by doflamingo721

Linked issue: https://github.com/rancher/rancher/issues/41751

2023-06-29 16:42 UTC, jiaqiluo requested changes

2023-06-29 16:42 UTC, jiaqiluo commented on pkg/rke/k8s_rke_system_images.go
> +			MetricsServer:             "rancher/mirrored-metrics-server:v0.6.2",
Is this change expected: 0.6.3 -> 0.6.2?

2023-06-29 18:03 UTC, doflamingo721 commented on pkg/rke/k8s_rke_system_images.go
> +			MetricsServer:             "rancher/mirrored-metrics-server:v0.6.2",
@jiaqiluo The earlier bump was not required. The previous available template had metric-server version `v0.6.2`. So reverted it back to the previous version.

2023-06-29 18:19 UTC, jiaqiluo approved these changes

2023-06-30 04:45 UTC, kinarashah approved these changes

2023-06-30 04:49 UTC, merged