[v2.7] K3S patch releases
rancher/kontainer-driver-metadata pull request #1188
Opened 2023-07-21 00:57 UTC by Tashima42

2023-07-28 16:48 UTC, johnatasr submitted a review, later dismissed

2023-07-28 18:54 UTC, rancher-max requested changes
I see that you removed the `vpn-auth` stuff from the `serverArgs` for the previous v1.26 release. Can we do the same for the previous v1.25 release (v1.25.11) as they only need to be present in the agentArgs when they apply to both?

Other than that, this LGTM. It's just fixing stuff from the previous versions 👍

2023-07-28 20:08 UTC, rancher-max requested changes

2023-07-28 20:08 UTC, rancher-max commented on channels.yaml
> +    serverArgs: *serverArgs-v3
I think this should be still be `*serverArgs-v4`

2023-07-28 20:08 UTC, rancher-max commented on channels.yaml
> +        type: string
This can just use `*serverArgs-v5` I think

2023-07-28 20:08 UTC, rancher-max commented on channels.yaml
> +    serverArgs: *serverArgs-v6
This should probably pull from `serverArgs-v4` and then include the `helm-job-image` to eventually have its own `&serverArgs-v6`

2023-07-31 16:00 UTC, rancher-max commented
https://github.com/rancher/rancher/issues/42115

2023-07-31 21:32 UTC, rancher-max approved these changes
LGTM

2023-08-01 20:00 UTC, merged

2023-08-02 12:28 UTC, vardhaman22 commented
@Tashima42  this PR has some  [docker info related changes](https://github.com/rancher/kontainer-driver-metadata/pull/1188/files#diff-d01a2c7a3b562201db5cb878080d51541026cccb36734541963bf2a41246cab4) which were not supposed to go with july 2023 patches, so this needs to be reverted.
cc: @kinarashah @snasovich @mitulshah-suse

2023-08-02 17:58 UTC, Tashima42 commented
Hi, @vardhaman22 this PR has been [reverted](https://github.com/rancher/kontainer-driver-metadata/pull/1191) and a new one with only the k3s patch release updates has been [merged](https://github.com/rancher/kontainer-driver-metadata/pull/1194)