[v2.7] Bump dependencies
rancher/kontainer-driver-metadata pull request #1189
Opened 2023-07-27 13:31 UTC by pjbgf

- github.com/rancher/rke v1.4.7
- github.com/sirupsen/logrus v1.9.3
- github.com/stretchr/testify v1.8.4
- k8s.io/apimachinery v0.25.12
- sigs.k8s.io/yaml v1.3.0
- k8s.io/client-go v0.25.12
- github.com/aws/aws-sdk-go v1.44.309
- github.com/docker/docker v20.10.24+incompatible
- golang.org/x/net v0.12.0
- golang.org/x/sys v0.10.0
- golang.org/x/text v0.11.0

2023-08-08 19:34 UTC, jiaqiluo approved these changes, later dismissed
LGTM. 
`go generate  .` does not produce any changes.

2023-09-29 13:16 UTC, pjbgf commented
Rebased + resolved conflicts.

2023-09-29 17:38 UTC, jiaqiluo requested changes

2023-09-29 17:38 UTC, jiaqiluo commented on go.mod
> +	github.com/rancher/rke v1.4.7
```suggestion
	github.com/rancher/rke v1.4.10
```

2023-10-06 23:51 UTC, jiaqiluo submitted a review, later dismissed

2024-02-21 13:48 UTC, pjbgf commented
Is there anything blocking this to be merged?

2024-02-29 12:23 UTC, pjbgf commented
Updated PR description for context, rebased the PR and added additional bump for `x/net`. PTAL

2024-03-20 21:38 UTC, snasovich commented
@jiaqiluo , this looks to be fully superseded by https://github.com/rancher/kontainer-driver-metadata/pull/1359 ?
If correct, let's close this one.

2024-03-20 21:44 UTC, jiaqiluo commented
Closing this PR in favor of https://github.com/rancher/kontainer-driver-metadata/pull/1359

2024-03-20 21:44 UTC, closed without merging