[v2.6] Bump dependencies
rancher/kontainer-driver-metadata pull request #1190
Opened 2023-07-27 13:46 UTC by pjbgf

- github.com/rancher/rke v1.4.7
- github.com/sirupsen/logrus v1.9.3
- github.com/stretchr/testify v1.8.4
- sigs.k8s.io/yaml v1.3.0
- k8s.io/client-go v0.25.12
- github.com/docker/docker v20.10.24+incompatible
- golang.org/x/net v0.12.0
- golang.org/x/sys v0.10.0
- golang.org/x/text v0.11.0

2023-08-08 19:36 UTC, jiaqiluo approved these changes

2023-09-29 13:22 UTC, pjbgf commented
rebased

2023-09-29 17:31 UTC, jiaqiluo approved these changes

2023-09-29 17:37 UTC, jiaqiluo requested changes

2023-09-29 17:37 UTC, jiaqiluo commented on go.mod
> +	github.com/rancher/rke v1.4.7
KDM 2.6 line is used in RKE 1.3 

```suggestion
	github.com/rancher/rke v1.3.24
```

2023-10-06 23:50 UTC, jiaqiluo approved these changes

2024-02-21 13:48 UTC, pjbgf commented
Is there anything blocking this to be merged?

2024-02-29 12:06 UTC, closed without merging