Bump calico and canal to v3.26.1
rancher/kontainer-driver-metadata pull request #1206
Opened 2023-08-21 16:53 UTC by doflamingo721

Linked issue: https://github.com/rancher/rancher/issues/41840

2023-08-29 23:39 UTC, jiaqiluo requested changes

2023-08-29 23:39 UTC, jiaqiluo commented on pkg/rke/templates/calico_v3.26.go
> +          image: docker.io/calico/cni:v3.26.1
need to be done at multiple places 
```suggestion
          image: {{.CNIImage}}
```

2023-08-29 23:39 UTC, jiaqiluo commented on pkg/rke/templates/canal_v3.26.go
> +https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/canal.yaml
```suggestion
https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/canal.yaml
```

2023-08-30 14:01 UTC, rayandas commented on pkg/rke/templates/calico_v3.26.go
> +          image: docker.io/calico/cni:v3.26.1
Fixed it

2023-08-30 14:01 UTC, rayandas commented on pkg/rke/templates/canal_v3.26.go
> +https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/canal.yaml
Updated the PR

2023-08-30 16:13 UTC, jiaqiluo submitted a review, later dismissed
LGTM

2023-08-31 06:11 UTC, rayandas commented
@jiaqiluo Sorry, earlier template wasn't working. So I did a fresh template update and tested it and it's working now. Could you please review once?
cc: @kinarashah @doflamingo721

2023-08-31 17:25 UTC, jiaqiluo approved these changes

2023-08-31 20:05 UTC, kinarashah approved these changes

2023-08-31 20:07 UTC, merged