[dev-v.2.8] k3s August patch release
rancher/kontainer-driver-metadata pull request #1223
Opened 2023-09-05 22:47 UTC by johnatasr

2023-09-07 17:15 UTC, brooksn submitted a review, later dismissed

2023-09-07 17:34 UTC, dereknola approved these changes

2023-09-07 17:43 UTC, dereknola requested changes, later dismissed

2023-09-07 17:43 UTC, dereknola commented on channels.yaml
> +    maxChannelServerVersion: v2.7.99
This is for v2.8, so we need to bump the min and max server versions correct?

2023-09-07 17:48 UTC, ShylajaDevadiga commented on channels.yaml
> +    maxChannelServerVersion: v2.7.99
Also for all k3s versions

2023-09-07 19:38 UTC, dereknola commented on channels.yaml
> +    maxChannelServerVersion: v2.7.99
```suggestion
    maxChannelServerVersion: v2.8.99
```

2023-09-07 19:39 UTC, dereknola commented on channels.yaml
> +    maxChannelServerVersion: v2.7.99
```suggestion
    minChannelServerVersion: v2.8.0-alpha1
    maxChannelServerVersion: v2.8.99
```

2023-09-07 22:50 UTC, brandond submitted a review, later dismissed

2023-09-08 01:40 UTC, brooksn commented on data/data.json
> +    "maxChannelServerVersion": "v2.7.99",
```suggestion
    "maxChannelServerVersion": "v2.8.99",
```

2023-09-08 01:54 UTC, brooksn submitted a review, later dismissed

2023-09-08 01:55 UTC, briandowns submitted a review, later dismissed

2023-09-08 02:03 UTC, briandowns approved these changes

2023-09-08 02:05 UTC, brooksn approved these changes

2023-09-08 02:10 UTC, merged