[dev-v2.8] RKE2 September patch releases
rancher/kontainer-driver-metadata pull request #1233
Opened 2023-09-14 02:29 UTC by brooksn

2023-09-19 16:12 UTC, rancher-max requested changes

2023-09-19 16:12 UTC, rancher-max commented on channels-rke2.yaml
> +    minChannelServerVersion: v2.8.0-alpha1
This should still be `v2.7.2-alpha1`

2023-09-19 16:12 UTC, rancher-max commented on channels-rke2.yaml
> +    minChannelServerVersion: v2.8.0-alpha1
This should still be `v2.7.5-alpha1`

2023-09-19 16:34 UTC, rancher-max requested changes

2023-09-19 16:34 UTC, rancher-max commented on channels-rke2.yaml
> +    minChannelServerVersion: v2.7.5-alpha1
`v2.7.2-alpha1` for v1.25 still

2023-09-20 16:47 UTC, rancher-max approved these changes

2023-09-20 20:57 UTC, johnatasr approved these changes

2023-09-21 15:52 UTC, ShylajaDevadiga approved these changes

2023-09-21 16:27 UTC, merged