[dev-v2.8] KDM Update for K8s September patch release
rancher/kontainer-driver-metadata pull request #1235
Opened 2023-09-15 09:38 UTC by chiukapoor

## Updates
- Add k8s 1.25.14
- Add k8s 1.26.9
- Add k8s 1.27.6
- Remove k8s 1.27.5
- Update default k8s to 1.27.6
- go generate

## Issue
- https://github.com/rancher/rancher/issues/42812

2023-09-22 17:30 UTC, jiaqiluo approved these changes
overall LGTM, just one thing to fix.

2023-09-22 17:34 UTC, jiaqiluo requested changes

2023-09-22 17:34 UTC, jiaqiluo commented on pkg/rke/k8s_version_info.go
Just realized that we need to bump the default version used for Rancher to `v1.27.x` at line 49.  
(GH does not allow me to comment on unchanged lines)

2023-09-25 04:39 UTC, chiukapoor commented on pkg/rke/k8s_version_info.go
Updated the default version.

2023-09-25 16:50 UTC, jiaqiluo approved these changes

2023-09-26 04:45 UTC, merged