Add docs for updating rancher/rancher before final RC's.
rancher/kontainer-driver-metadata pull request #1245
Opened 2023-09-26 22:20 UTC by HarrisonWAffel

This adds explicit docs to cover the changes related to KDM that must be made in rancher/rancher before a final RC is cut.

2023-09-26 22:46 UTC, jiaqiluo approved these changes, later dismissed

2023-10-18 18:30 UTC, a-blender requested changes
I would be a little more specific here,

```
Rancher references a particular KDM branch in the Dockerfiles and settings file within its code base.
```

Otherwise, you make it sound like different KDM branches are being referenced at one time which is not true. It's either one dev or release branch, globally. Rephrase the 90%, unless that stat came from somewhere?

Suggestion
```
Updated from a dev branch to point at a release branch
```

There's also two instances of `Preparing/when preparing for a rancher/rancher release. In general, this part can be consolidated a little better.

2023-10-18 18:48 UTC, a-blender requested changes
I would be more specific here,

```
Rancher references a particular KDM branch in the Dockerfiles and settings file within its code base.
```

Otherwise, you make it sound like different KDM branches are being referenced at one time which is not true. It's either one dev or release branch, globally. Rephrase the 90%, unless that stat came from somewhere?

Suggestion
```
Updated from a dev branch to point at a release branch
```

There's also two instances of `Preparing/when preparing for a rancher/rancher release. In general, this part can be consolidated a little better.

2023-10-18 19:17 UTC, a-blender approved these changes

2024-02-24 00:59 UTC, jiaqiluo approved these changes

2024-03-05 21:54 UTC, merged