[v2.7] k8s october 2023 patches
rancher/kontainer-driver-metadata pull request #1257
Opened 2023-10-25 11:15 UTC by vardhaman22

2023-11-14 16:26 UTC, snasovich requested changes
@vardhaman22 , please update `rke-tools` to `v0.1.96`. While at it, could you please also update it in previous versions as done per https://github.com/rancher/kontainer-driver-metadata/pull/1259 (in fact, please bring in other changes that got into `dev-v2.7-2023-09-patches` branch after we branched for `dev-v2.7-2023-10-patches` - e.g. RKE2/k3s R2 releases).

2023-11-15 12:45 UTC, vardhaman22 commented
> @vardhaman22 , please update `rke-tools` to `v0.1.96`. While at it, could you please also update it in previous versions as done per #1259 (in fact, please bring in other changes that got into `dev-v2.7-2023-09-patches` branch after we branched for `dev-v2.7-2023-10-patches` - e.g. RKE2/k3s R2 releases).

rebased my branch with  `dev-v2.7-2023-09-patches`  and also updated rke-tools image to v0.1.96 in the latest changes.

2023-12-04 14:40 UTC, kinarashah commented on pkg/rke/templates/calico_v3.36.go
file name: calico_v3.26.go

2023-12-04 14:52 UTC, vardhaman22 commented on pkg/rke/templates/calico_v3.36.go
updated

2023-12-04 16:01 UTC, kinarashah approved these changes, later dismissed
- confirmed the k8s system images are same as v2.8 PR 
- confirmed default k8s version 
- confirmed addon versions in templates.go

2023-12-06 03:11 UTC, snasovich submitted a review, later dismissed

2023-12-06 03:14 UTC, snasovich commented
LGTM. From what I can see this includes ensuring we have changes that were released per Sep patches into this branch too.

Also, I have removed references to 2.8 issues in the description of this PR.

2023-12-06 15:23 UTC, snasovich approved these changes
LGTM, thank you for addressing https://github.com/rancher/kontainer-driver-metadata/pull/1256#discussion_r1416611256

2023-12-06 16:11 UTC, kinarashah approved these changes

2023-12-06 16:50 UTC, merged