Add rancher integration tests to CI
rancher/kontainer-driver-metadata pull request #1289
Opened 2023-12-19 21:36 UTC by jakefhyde

https://github.com/rancher/rancher/issues/43585

I did experiment with running rancher as a docker container, as well as within k3d, but removed it due to unknowns surrounding networking. I was able to get it working by adding the currently running dapper container to the docker network I was creating both the rancher container, as well as the k3d instance, but there were too many unknowns regarding behavior of concurrent workers, so I opted to instead run rancher itself, as this is already an established baseline from within rancher itself. 

## Todo

- Pin rancher commit to rancher image if unspecified
- Remove unneeded items from dockerfile (copied 1-1 from rancher)
- Improve some of the scripting in `extract-rancher`

2024-01-18 19:13 UTC, jiaqiluo requested changes

2024-01-18 19:13 UTC, jiaqiluo commented on scripts/provisioning-tests
> +if [[ -n DIST ]]; then
Hmm, where is the env var  `DIST` set? 
Also, do you want to overwrite its value to `k3s` when it is set? I feel what we need is the opposite. Can you confirm?

2024-01-29 21:09 UTC, jakefhyde commented on scripts/provisioning-tests
> +# TODO: replace 1989024f0e122d6be84263021d9ad438ed7ce69e with HEAD~1
I will address this todo comment once the PR has been approved. I am doing it this way to ensure the tests still run and the drone output is viewable and correct.

2024-01-30 02:16 UTC, jakefhyde commented
This PR is (finally) ready to review.

Currently waiting for drone build to pass, as there are 12 steps that must run.

- I updated the `Dockerfile.dapper` to use a multi-stage approach, such that it merely copies the important assets the rancher/rancher build container uses to be able to run rancher with an embedded k3s. 
- There is are two pipelines each for the `Provisioning` and `Test_Operation_SetA_` test cases for each rancher supported kubernetes minor version of both RKE2 and K3s respectively. This is currently 12 separate pipelines, 4 for each minor version (1.25, 1.26, and 1.27). Given that the `Test_Operation_SetA_` and `Test_Operation_SetB_` suites test provisioning (as a byproduct), I am open to discussion on changing this regex if it is deemed unreasonable.
- I opted to use `^Test_(Provisioning|Operation)_.*$` as a test regex when not running in CI, as this will cover P0 provisioning cases as well as day 2 ops. 
- I am planning to monitor new PRs which add RKE2/K3s versions, and maintain the integration of these provisioning tests.

2024-01-30 17:14 UTC, Oats87 approved these changes, later dismissed
LGTM. The only real comment I have is regarding your comment here:
>I am planning to monitor new PRs which add RKE2/K3s versions, and maintain the integration of these provisioning tests.

This is probably not realistic to keep as a "human-based" task. Is it possible to define a GitHub action that would verify the .drone.yml` has the expected number of pipelines based on the channels files? Not a blocking request though.

2024-01-30 17:14 UTC, Oats87 commented on scripts/provisioning-tests
> +./scripts/provisioning-tests
nit: eof

2024-01-30 23:12 UTC, jiaqiluo requested changes

2024-01-30 23:12 UTC, jiaqiluo commented on scripts/provisioning-tests
> +  V2PROV_TEST_RUN_REGEX="^Test_(Provisioning|Operation)_.*$"
Should we expert the env var V2PROV_TEST_RUN_REGEX, similar to the above V2PROV_TEST_DIST? 
```suggestion
  V2PROV_TEST_RUN_REGEX="^Test_(Provisioning|Operation)_.*$"
  export V2PROV_TEST_RUN_REGEX
```

2024-01-31 16:57 UTC, jakefhyde commented on scripts/provisioning-tests
> +  V2PROV_TEST_RUN_REGEX="^Test_(Provisioning|Operation)_.*$"
Good call

2024-01-31 16:58 UTC, jakefhyde commented
@Oats87 @jiaqiluo Addressed @jiaqiluo's review comments and changed the commit to `HEAD~1`. The pipelines should all exit early since there are no tests to run.

2024-01-31 18:46 UTC, jiaqiluo submitted a review, later dismissed

2024-01-31 18:47 UTC, jiaqiluo commented on scripts/test-run-required.sh
> +# TODO: replace 1989024f0e122d6be84263021d9ad438ed7ce69e with HEAD~1
nit: remove this comment?

2024-01-31 19:09 UTC, jiaqiluo approved these changes

2024-01-31 19:31 UTC, merged