Kdm march 2024 27
rancher/kontainer-driver-metadata pull request #1361
Opened 2024-03-19 21:32 UTC by briandowns

2024-03-20 23:56 UTC, rancher-max requested changes
One thing on rke2, otherwise lgtm and will give official approval once we have non-rc versions. Thank you!

2024-03-20 23:56 UTC, rancher-max commented on channels-rke2.yaml
> +    minChannelServerVersion: v2.8.0-alpha1
@briandowns when updating for the non-rc versions, we should also change this to be `v2.7.11-alpha1` so that it is present in the v2.7 release line

2024-03-21 16:41 UTC, rancher-max commented on channels-rke2.yaml
> +    minChannelServerVersion: v2.8.0-alpha1
```suggestion
    minChannelServerVersion: v2.7.11-alpha1
```

2024-03-21 22:31 UTC, rancher-max submitted a review, later dismissed
LGTM for rke2
k3s also looks good but is currently still going through QA validations in this rc stage 👍

2024-03-26 16:38 UTC, rancher-max requested changes

2024-03-26 16:38 UTC, rancher-max commented on channels-rke2.yaml
> +        repo: rancher-charts
This should be `rancher-rke2-charts`

2024-03-26 16:38 UTC, rancher-max commented on channels-rke2.yaml
> +        repo: rancher-charts
This should also be `rancher-rke2-charts`

2024-03-26 16:44 UTC, rancher-max approved these changes

2024-03-26 19:05 UTC, cwayne18 approved these changes

2024-03-26 19:08 UTC, brandond approved these changes

2024-03-26 20:38 UTC, merged