Sync changes from dev-v2.8 to dev-v2.9
rancher/kontainer-driver-metadata pull request #1362
Opened 2024-03-20 20:13 UTC by kinarashah

2024-03-20 22:00 UTC, jiaqiluo requested changes

2024-03-20 22:00 UTC, jiaqiluo commented on Dockerfile.dapper
> +FROM rancher/rancher:$RANCHER_VERSION as rancher
Should it be `v2.9-head`? The tag v2.9-head exists in [DockerHub](https://hub.docker.com/layers/rancher/rancher/v2.9-head/images/sha256-64b5c5265107846ba19a514ba74b953ddbbdb95b182d3094c211b455bf9950c7?context=explore).

2024-03-20 22:00 UTC, jiaqiluo commented on pkg/images/images.go
> +		if min.GE(v290) {
Currently, the function returns false for any RKE version that is available in Rancher v2.9.x, we should raise the upper limit to v2.9.10 ( multiple changes are needed in this file and the testing file).

2024-03-20 22:02 UTC, jiaqiluo commented
I left a few comments, and I am also OK if there is a follow-up PR to address my comments.

2024-03-20 23:35 UTC, kinarashah commented on pkg/images/images.go
> +		if min.GE(v290) {
Ah, I thought GE v290 would take care of all v2.9 versions but looks like not. I'll update this and the test file

2024-04-04 00:42 UTC, kinarashah commented
Closing in favor of https://github.com/rancher/kontainer-driver-metadata/pull/1373, GH didn't allow me to change the base branch and needed to push more changes.

2024-04-04 00:42 UTC, closed without merging