[v2.9] k8s Aug 2024 Patches
rancher/kontainer-driver-metadata pull request #1473
Opened 2024-08-24 12:03 UTC by chiukapoor

## Updates
- Added k8s version v1.28.13, v1.29.8, v1.30.4 (August Patch) 

## Related
- https://github.com/rancher/rancher/issues/46715

2024-09-03 23:05 UTC, kinarashah requested changes

2024-09-03 23:05 UTC, kinarashah commented on pkg/rke/templates/nginx-v1.11.2-rancher1.go
> +    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
we shouldn't need these annotations as we're doing static deploy and not deploying via helm chart

2024-09-03 23:05 UTC, kinarashah commented on pkg/rke/templates/nginx-v1.11.2-rancher1.go
> +- rearranged the file to match the upstream
Upstream changelog is only needed for new changes that were introduced upstream to keep track, don't need this here

2024-09-03 23:05 UTC, kinarashah commented on pkg/rke/templates/nginx-v1.11.2-rancher1.go
> -- added an enable-mertics=false arg in controller container of DaemonSet nginx-ingress-controller
We still have `enable-metrics=false` in the daemonset

2024-09-03 23:05 UTC, kinarashah commented on pkg/rke/templates/nginx-v1.11.2-rancher1.go
> +      - secrets
Upstream still has `namespaces` permission for ClusterRole, are we intentionally removing it? https://github.com/kubernetes/ingress-nginx/blob/e9259af906f462ff052e9fd80247945d1fb7f661/deploy/static/provider/cloud/deploy.yaml#L163

2024-09-03 23:05 UTC, kinarashah commented on pkg/rke/k8s_rke_system_images.go
> +		// Enabled out of band post Rancher v2.9.2
Enabled in Rancher v2.9.0 for all versions

2024-09-03 23:05 UTC, kinarashah commented on pkg/rke/k8s_version_info.go
> +		"2.8.7":        "v1.28.x",
I think we don't need these as the branch is for 2.9 only, but it's not a breaking change. (I see the versions prior to 2.8.4 already existed, so maybe that's why it's getting maintained.)

2024-09-04 06:36 UTC, chiukapoor commented on pkg/rke/templates/nginx-v1.11.2-rancher1.go
> +    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
helm annotations are already part of our existing nginx template

https://github.com/rancher/kontainer-driver-metadata/blob/cbfb93a34198103221d37ff82dc46c5b85db6949/pkg/rke/templates/nginx-v1.9.6-rancher1.go#L581-L582

If these are not used anymore I can update the latest nginx template to remove it

2024-09-04 06:48 UTC, chiukapoor commented on pkg/rke/templates/nginx-v1.11.2-rancher1.go
> +      - secrets
It is not present in the previous nginx template although upstream has added `namespaces` permission a couple of years ago. Assuming this was missed adding it in the latest nginx template

2024-09-04 06:54 UTC, chiukapoor commented on pkg/rke/k8s_rke_system_images.go
> +		// Enabled out of band post Rancher v2.9.2
Assuming it is `Enabled in Rancher v2.9.2`, updated the code accordingly. Please correct me if it needs to be `v2.9.0`

2024-09-04 15:31 UTC, kinarashah commented on pkg/rke/k8s_rke_system_images.go
> +		// Enabled out of band post Rancher v2.9.2
sorry, yeah v2.9.2 😅

2024-09-04 16:45 UTC, kinarashah approved these changes

2024-09-06 07:19 UTC, merged