[v2.10] Add ACI CNI 6.1.1.1 template changes
rancher/kontainer-driver-metadata pull request #1518
Opened 2024-10-15 09:22 UTC by akhilesh-oc

https://github.com/rancher/rancher/issues/47413

2024-10-16 16:53 UTC, kinarashah requested changes
Could you update ACI versions for `v1.31.1-rancher1-1` as well?

2024-10-22 19:43 UTC, kinarashah requested changes
@akhilesh-oc Need to run `go generate` and commit updated data.json.

2024-10-23 15:51 UTC, snasovich approved these changes

2024-10-23 15:52 UTC, kinarashah approved these changes

2024-10-23 15:52 UTC, merged