[v2.10] k8s November 2024 Patches
rancher/kontainer-driver-metadata pull request #1557
Opened 2024-11-26 06:50 UTC by krunalhinguu

### Updates

- Added k8s version 1.29.11 for November Patches
- Added k8s version 1.30.7 for November Patches
- Added k8s version 1.31.3 for November Patches

### Related

- https://github.com/rancher/rancher/issues/48083

2024-11-28 01:04 UTC, kinarashah requested changes

2024-11-28 01:04 UTC, kinarashah commented on pkg/rke/templates/calico_v3.29.0.go
> +                          maximum: 32
Something seems off here. Upstream's maximum is set to a default value, was this not updated earlier or it's not picked from upstream now? https://raw.githubusercontent.com/projectcalico/calico/v3.29.0/manifests/canal.yaml

2024-11-28 01:04 UTC, kinarashah commented on pkg/rke/templates/calico_v3.29.0.go
> +                          maximum: 32
Same as above. https://www.diffchecker.com/1XGIbsAP/ for the full diff.

2024-11-28 02:23 UTC, krunalhinguu commented
updated @kinarashah

2024-11-28 04:52 UTC, kinarashah requested changes
@krunalhinguu Same changes required for canal too

2024-11-29 04:41 UTC, kinarashah approved these changes

2024-11-29 04:42 UTC, merged