[v2.10] Bump ingress-backend
rancher/kontainer-driver-metadata pull request #1564
Opened 2024-12-04 06:40 UTC by chiukapoor

### Updates
- Bump ingress-backend to `1.5-rancher2 `

### Issue
- https://github.com/rancher/rancher/issues/48034

2024-12-05 17:24 UTC, jiaqiluo requested changes

2024-12-05 17:24 UTC, jiaqiluo commented on pkg/rke/k8s_rke_system_images.go
Based on [the comparison](https://github.com/rancher/kontainer-driver-metadata/compare/release-v2.10...dev-v2.10), there will be 3 new versions to be released: v1.29.11-rancher1-1, v1.30.7-rancher1-1, and v1.31.3-rancher1-1. 

it looks like the template for v1.31.3-rancher1-1 is not updated in the PR.

2024-12-06 05:24 UTC, chiukapoor commented on pkg/rke/k8s_rke_system_images.go
Updated

2024-12-06 16:03 UTC, jiaqiluo approved these changes
lgtm

2024-12-06 17:41 UTC, snasovich requested changes
Since this is not getting released with v2.10.1, we will need to redo this PR to target versions to be added for v2.10.2 instead.

2024-12-23 05:34 UTC, closed without merging