[dev-v2.5] Bump etcd to v3.4.15
rancher/kontainer-driver-metadata pull request #524
Opened 2021-04-07 11:40 UTC by superseb

2021-04-12 20:03 UTC, PennyScissors requested changes
The image `rancher/mirrored-coreos-etcd:v3.4.15-rancher1` is missing from the images list in rancher/image-mirror [here](https://github.com/rancher/image-mirror/blob/bbe92d1d7162f88b2ad8d122006e2dcf71433a6e/images-list#L253-L256).

2021-04-13 15:40 UTC, superseb commented
Fixed via https://github.com/rancher/image-mirror/pull/90

2021-04-13 18:59 UTC, PennyScissors approved these changes

2021-04-15 22:31 UTC, kinarashah commented on rke/k8s_rke_system_images.go
> +			Etcd:                      "rancher/mirrored-coreos-etcd:v3.4.15-rancher1",
Are we updating etcd for v1.17.x? `We are consciously not updating k8s 1.17 as k8s is no longer supporting 1.17.`

2021-04-15 23:28 UTC, kinarashah reviewed
Sorry @superseb, but since we are now reserving `rancher1-2` as a 2.4 copy for ACI images, we'd now need to use `rancherX-3` instead of `rancherX-2` for `v1.17.x` and `v1.18.x`.

2021-04-16 22:57 UTC, PennyScissors commented
Closed in favor of these (bumped etcd in PRs for new k8s versions):
https://github.com/rancher/kontainer-driver-metadata/pull/534
https://github.com/rancher/kontainer-driver-metadata/pull/535

2021-04-16 22:58 UTC, PennyScissors commented
Closed in favor of these (bumped etcd in PRs for new k8s versions): https://github.com/rancher/kontainer-driver-metadata/pull/534, https://github.com/rancher/kontainer-driver-metadata/pull/535

2021-04-16 22:58 UTC, closed without merging