[dev-2.6] Upgrade rke2 versions
rancher/kontainer-driver-metadata pull request #559
Opened 2021-05-22 00:09 UTC by dweomer

- rke2 bumps:
- go generate (rke2 bumps)

2021-05-22 00:13 UTC, davidnuzik commented
Version bumps LGTM, would like @kinarashah to review as I don't grok the 2.6 changes in KDM and ensure what's in the yaml is good to go.

2021-05-26 05:18 UTC, davidnuzik commented on channels-rke2.yaml
> +  - version: v1.20.7+rke2r1
@dweomer can you bump to v1.20.7+rke2r2 at your convenience this week?

2021-05-26 05:18 UTC, davidnuzik requested changes
bump to v1.20.7+rke2r2

2021-06-01 16:06 UTC, kinarashah approved these changes

2021-06-01 21:39 UTC, davidnuzik approved these changes

2021-06-01 21:42 UTC, davidnuzik commented
@kinarashah think we can merge this? Or are we not comfortable yet? e.g. I'm thinking about @ibuildthecloud 's changes in 2.6 and the new entries in channels yaml like the [charts](https://github.com/rancher/kontainer-driver-metadata/pull/559/files#diff-a0456795a97052d90c30065cde4425e798e52b4a119590fc8a7e66416ec5ce61R11), serverArgs, etc, etc. I don't grok the changes in 2.6 dev branch, and so I don't necessarily feel comfortable merging this in...

2021-06-01 21:51 UTC, kinarashah commented
@davidnuzik Based on what I understand, those entries don't affect v1.18 and v1.19. 
For v1.20, it was already in use so bumping k8s version should be good because what worked for `v1.20.5` will work for `v1.20.7`. But I could be wrong because I don't fully understand those args either. 

Anyway, it's a dev branch and we don't have a release-v2.6 planned anytime soon, so I'd say let's merge and get it to test so we'll know what needs to be fixed. Worst case, we revert in case of blocker issues. 

Thoughts?

2021-06-01 22:33 UTC, davidnuzik commented
@kinarashah gotcha. And yes, very true no 2.6 releases any time very soon I believe. Ok let's merge this.

2021-06-01 22:50 UTC, merged