[WIP] Update rke2 releases august 2021
rancher/kontainer-driver-metadata pull request #668
Opened 2021-08-26 23:19 UTC by briandowns

2021-08-26 23:59 UTC, cwayne18 submitted a review, later dismissed

2021-08-27 14:54 UTC, deniseschannon commented
https://github.com/rancher/rancher/issues/33880

2021-08-27 14:54 UTC, deniseschannon requested changes

2021-08-27 14:54 UTC, deniseschannon commented on channels-rke2.yaml
> -  - version: v1.21.4-rc1+rke2r1
I would like this PR to also include removing the 1.21.3 release to prep for the 2.6 release.

2021-08-27 15:10 UTC, briandowns commented on channels-rke2.yaml
> -  - version: v1.21.4-rc1+rke2r1
1.21.3 removed

2021-08-27 16:04 UTC, deniseschannon commented
Small nit: can you update from &charts to &charts-v1?

2021-08-27 16:07 UTC, briandowns commented
Updated.

2021-08-27 17:49 UTC, deniseschannon approved these changes

2021-08-27 17:49 UTC, deniseschannon commented
Please do not merge until given the green light as this will remove having 2 versions of RKE2 in our release.

2021-08-28 18:11 UTC, merged