rke2: cilium: Update the chart to 1.10.401
rancher/kontainer-driver-metadata pull request #682
Opened 2021-09-09 13:28 UTC by vadorovsky

https://github.com/cilium/cilium/releases/tag/v1.10.4

Ref: rancher/rke2#1615

Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

2021-09-09 16:24 UTC, briandowns submitted a review, later dismissed

2021-09-09 16:25 UTC, dereknola approved these changes, later dismissed

2021-09-09 16:26 UTC, brandond requested changes
This needs to go in a new version section - see 
https://github.com/rancher/kontainer-driver-metadata/pull/652#issuecomment-915457725

You may want to just wait and rebase this once that PR is merged.

2021-09-10 11:21 UTC, vadorovsky commented
@brandond Ok. Since the new version is added in the PR you linked, I will just put this one on hold.

2021-09-14 07:31 UTC, vadorovsky commented
@brandond should be ready now

2021-09-14 08:32 UTC, brandond approved these changes

2021-09-28 00:10 UTC, deniseschannon commented
Based on this PR, I think this could be closed? https://github.com/rancher/kontainer-driver-metadata/pull/693

2021-09-28 00:11 UTC, dereknola commented
Yes this PR has been superseded by https://github.com/rancher/kontainer-driver-metadata/pull/693

2021-09-28 00:47 UTC, closed without merging