Release Flannel bumps to v0.15.1
rancher/kontainer-driver-metadata pull request #746
Opened 2021-12-02 19:08 UTC by aiyengar2

QA has finished testing, so we should be good to release.

Original PR: https://github.com/rancher/kontainer-driver-metadata/pull/736

Related Issue: https://github.com/rancher/rancher/issues/35245

2021-12-02 20:06 UTC, kinarashah approved these changes

2021-12-02 20:30 UTC, PennyScissors requested changes
The changes for version info and new default in k8s_version_info.go are missing

2021-12-03 00:17 UTC, aiyengar2 commented
> The changes for version info and new default in [k8s_version_info.go](https://github.com/rancher/kontainer-driver-metadata/blob/7d171a7bbb4af7b8fa67d2f58729895bfa5bc7cc/rke/k8s_version_info.go#L41) are missing

@PennyScissors discussed with this @kinarashah offline and we decided to not bump the default version in this release. We'll bump as part of the Nov k8s patch releases, since this is a one-off release just for CentOS 8 support

2021-12-03 00:42 UTC, PennyScissors approved these changes

2021-12-03 00:52 UTC, merged