February rke2 rcs 1.21 & 1.22
rancher/kontainer-driver-metadata pull request #833
Opened 2022-02-18 22:41 UTC by briandowns

2022-02-18 22:46 UTC, brandond submitted a review, later dismissed

2022-02-18 22:51 UTC, brandond requested changes

2022-02-18 22:51 UTC, brandond commented on channels-rke2.yaml
> +        version: v3.20.3-build2022011406
This appears to be the same chart version as in `charts-v1-22-6-rke2r1`; I think you can just use that anchor without any changes or even creating a new anchor.

2022-02-21 15:05 UTC, jossemargt-3pillar submitted a review, later dismissed

2022-02-22 21:16 UTC, rancher-max commented
We also need to update the default version at the top before we merge this (with the non-rc version once we release that)

2022-02-22 21:49 UTC, brandond requested changes

2022-02-22 21:49 UTC, brandond commented on channels-rke2.yaml
> +        version: v3.20.3-build2022011406
Actually it looks like it's changed: https://github.com/rancher/rke2/blob/release-1.22/Dockerfile#L102
```suggestion
        version: v3.21.4-build2022020801
```

2022-02-22 21:49 UTC, brandond commented on channels-rke2.yaml
> +        version: v3.20.3-build2022011406
https://github.com/rancher/rke2/blob/release-1.21/Dockerfile#L104
```suggestion
        version: v3.21.4-build2022020801
```

2022-02-23 17:19 UTC, rancher-max requested changes
It looks like we actually need to update `rke2-calico` version to `v3.21.401` on 1.22 as well:
https://github.com/rancher/rke2/blame/release-1.22/Dockerfile#L95-L112:

1.21 looks good:
https://github.com/rancher/rke2/blame/release-1.21/Dockerfile#L97-L116

2022-02-23 23:42 UTC, brandond approved these changes

2022-02-23 23:44 UTC, rancher-max approved these changes

2022-02-25 17:35 UTC, merged