[2.6] Add k8s February patch
rancher/kontainer-driver-metadata pull request #845
Opened 2022-03-07 07:42 UTC by doflamingo721

Linked issue:
https://github.com/rancher/rancher/issues/36435

Adds:
1.20.16-rancher1-1
1.21.10-rancher1-1
1.22.7-rancher1-1

2022-03-08 00:55 UTC, kinarashah requested changes
@doflamingo721 we have `rancher1-2` in dev-v2.6 for these versions that aren't merged in release-v2.6, so we can update those instead of adding new ones: 
```
1.20.15-rancher1-2 
1.21.9-rancher1-2
1.22.6-rancher1-2 
```

2022-03-08 14:29 UTC, samkulkarni20 commented
@kinarashah Vaishnav made the updates. Pls review.

2022-03-08 17:32 UTC, kinarashah approved these changes

2022-03-09 03:13 UTC, snasovich approved these changes
LGTM, going to merge to allow QA to get a headstart on testing.

2022-03-09 03:13 UTC, merged