Merge pull request#826from rancher/dev-v2.6
rancher/kontainer-driver-metadata pull request #846
Opened 2022-03-07 22:28 UTC by paynejacob

github.com/rancher/rancher/issues/36471

Bump flannel for k8s 1.22 and 1.23 to avoid host ports breaking on upgrade from 1.21

2022-03-07 23:03 UTC, kinarashah reviewed
There are a few changes upstream with v0.17.0 that we need to update in our template. 

@superseb https://github.com/flannel-io/flannel/blob/master/Documentation/kube-flannel.yml now uses rancher images, do you think we still need to maintain v116 template and pick upstream changes? or we can replace the whole template with upstream?

2022-03-09 17:14 UTC, kinarashah commented on rke/templates/templates.go
> +			">=1.22.0-alpha":                    flannelv0170,
we don't want to change what already released v1.22.x versions use, so this would be `>=v1.22.6-rancher1-2` and `>=1.21.0-alpha <1.22.6-rancher1-2`

2022-03-09 17:17 UTC, kinarashah reviewed
Infracloud team merged new Feb patch updates, so `v1.22.6-rancher1-2` is now replaced by `v1.22.7-rancher1-1` and we can bump flannel for `v1.22.7-rancher1-1` directly. 

(I am not sure why there were no conflicts when `v1.22.6-rancher1-2` no longer exists in `dev-v2.6`)

2022-03-10 20:07 UTC, kinarashah requested changes

2022-03-10 20:07 UTC, kinarashah commented on rke/templates/flannel.go
> +      maxUnavailable: 20%
I think `UpdateStrategy` block is missing `{{end}}`, could you confirm?

2022-03-10 20:07 UTC, kinarashah commented on rke/k8s_rke_system_images.go
> +			CanalFlannel:              "rancher/mirrored-coreos-flannel:v0.17.0",
we would also need to bump Flannel and FlannelCNI 
```
Flannel:                   "rancher/mirrored-coreos-flannel:v0.15.1",
FlannelCNI:             "rancher/flannel-cni:v0.3.0-rancher6",
```			
these would use the new flannel template so after updating it, we might need one round of testing to confirm flannel works as expected.

2022-03-10 20:07 UTC, kinarashah commented on rke/templates/flannel.go
> +        image: rancher/mirrored-flannelcni-flannel:v0.17.0
It'd be better not to hard code this image and use `image: {{.CNIImage}}`, especially for airgap use cases where the image list is generated from our system images. `CNIImage` is the `FlannelCNI` image passed by RKE from system images.

2022-03-10 20:10 UTC, kinarashah commented on rke/k8s_rke_system_images.go
> +			CanalFlannel:              "rancher/mirrored-coreos-flannel:v0.17.0",
based on an older conversation with @luthermonson, it should be okay to replace `flannel-cni:v0.3.0-rancher6` with new tag upstream. that's what upstream uses and we can be consistent with it unless we see any blocker issues with it.

2022-03-15 19:30 UTC, paynejacob commented
https://github.com/rancher/rke/pull/2868

2022-03-15 20:30 UTC, kinarashah approved these changes
Not updating flannel for 2.6.4, tracking https://github.com/rancher/rke/issues/2870

2022-03-16 16:13 UTC, thedadams approved these changes

2022-03-16 16:14 UTC, merged