Rke2 march releases
rancher/kontainer-driver-metadata pull request #863
Opened 2022-03-23 03:06 UTC by briandowns

2022-03-31 20:24 UTC, rancher-max requested changes
Made some suggestions for additions based on:
- https://github.com/rancher/rke2/blame/v1.21.11%2Brke2r1/Dockerfile#L98-L117
- https://github.com/rancher/rke2/blame/v1.22.8%2Brke2r1/Dockerfile#L99-L116
- https://github.com/rancher/rke2/blame/v1.23.5%2Brke2r1/Dockerfile#L101-L118

2022-03-31 20:24 UTC, rancher-max commented on channels-rke2.yaml
> +        version: 1.17.000
```suggestion
        version: 1.17.000
      rke2-ingress-nginx:
        repo: rancher-rke2-charts
        version: 4.0.307
```

2022-03-31 20:24 UTC, rancher-max commented on channels-rke2.yaml
> +        version: 1.17.000
```suggestion
        version: 1.17.000
      rke2-ingress-nginx:
        repo: rancher-rke2-charts
        version: 4.0.307
```

2022-03-31 20:24 UTC, rancher-max commented on channels-rke2.yaml
> +    minChannelServerVersion: v2.6.4-alpha1
```suggestion
    minChannelServerVersion: v2.6.3-alpha1
```

This is based off a change that was made to dev-v2.6 for the rancher release. Rebasing your branch should pull this in for v1.21.10+rke2r2 so this change is just to make it consistent with that.

2022-03-31 20:24 UTC, rancher-max commented on channels-rke2.yaml
> +        version: 1.17.000
```suggestion
        version: 1.17.000
      rke2-ingress-nginx:
        repo: rancher-rke2-charts
        version: 4.0.307
```

2022-03-31 20:48 UTC, rancher-max approved these changes

2022-04-06 16:47 UTC, dereknola approved these changes

2022-04-06 16:47 UTC, cwayne18 approved these changes

2022-04-06 16:48 UTC, merged