April release rke2
rancher/kontainer-driver-metadata pull request #885
Opened 2022-04-21 00:08 UTC by nikolaishields

2022-04-21 15:27 UTC, rancher-max requested changes

2022-04-21 15:27 UTC, rancher-max commented on channels-rke2.yaml
> +    latest: v1.22.9-rc2+rke2r1
I believe this is correct, but we should confirm with @kinarashah or @snasovich that v1.22 is the expected default for Rancher v2.6.5. I apologize if this confirmation has already happened and I just forgot.

2022-04-21 15:27 UTC, rancher-max commented on channels-rke2.yaml
> +      <<: *charts-v1-21-11-rke2r1
The server and agent args should also pull from v1-21-11-rke2r1 otherwise they will miss some of the changes that were present from those.

2022-04-21 15:27 UTC, rancher-max commented on channels-rke2.yaml
> +      <<: *charts-v1-22-8-rke2r1
The server and agent args should also pull from v1-22-8-rke2r1 otherwise they will miss some of the changes that were present from those.

2022-04-21 15:27 UTC, rancher-max commented on channels-rke2.yaml
> +      <<: *charts-v1-23-5-rke2r1
The server and agent args should also pull from v1-23-5-rke2r1 otherwise they will miss some of the changes that were present from those.

2022-04-21 16:13 UTC, kinarashah commented on channels-rke2.yaml
> +    latest: v1.22.9-rc2+rke2r1
@rancher-max afaik 1.22.x is still the default for v2.6.5, we can update it later to v1.23 if needed

2022-04-22 15:56 UTC, rancher-max approved these changes, later dismissed
LGTM but I think we should leave this unmerged and validate off your branch so that it is even more trivial to push the actual released versions in once we've gotten there. Also will help in case of more RCs.

2022-04-22 20:20 UTC, jiaqiluo commented
Not an issue but just FYI: 
Rancher v2.6.5 and above will make use of the newly added `appDefautls` directive to calculate the default version; v2.6.0 - 2.6.4 keep using the default channel to get the default version. 

With that said, we will keep updating the value in the channel for v2.6.0 - 2.6.4, the change will be only the bump of the patch version, unless we want to make, for example, 1.23.x  the default for 2.6.0 - 2.6.4

2022-04-26 17:30 UTC, rancher-max requested changes
This looks good, but the latest and greatest news is that we are NOT going to be releasing March patches. Current state is that those are present in dev-v2.6 KDM but are not present in release-v2.6. 
Sooo as part of this PR, can we remove v1.21.11+rke2r1, v1.22.8+rke2r1, and v1.23.5+rke2r1 (and do the necessary changes to ensure we still pull all the proper chart versions)?

2022-04-26 21:25 UTC, rancher-max approved these changes
LGTM

2022-04-27 01:02 UTC, merged