Release April 2022 k8s patches
rancher/kontainer-driver-metadata pull request #891
Opened 2022-04-26 20:46 UTC by kinarashah

2022-04-28 20:23 UTC, rancher-max reviewed
We will have channels.yaml and channels-rke2.yaml updated today in dev-v2.6 with the non-rc versions of the rke2/k3s releases, so if we can hold on this until that happens that would be ideal

2022-04-28 20:24 UTC, kinarashah commented
@rancher-max Yep! no rush, we're waiting for that - just getting PRs up for release so we can start reviewing and double check if anything else is missing.

2022-04-29 00:17 UTC, rancher-max submitted a review, later dismissed
LGTM and has been validated for both rke2 and k3s

2022-04-29 02:42 UTC, snasovich submitted a review, later dismissed

2022-04-29 03:03 UTC, rayandas requested changes

2022-04-29 03:03 UTC, rayandas commented on rke/k8s_version_info.go
> +		},
@kinarashah We decided to remove K8s march patches right? so 1.22.8-rancher1-1 shouldn’t be here.

2022-04-29 03:05 UTC, kinarashah commented on rke/k8s_version_info.go
> +		},
@rayandas good catch, thanks! fixing it

2022-04-29 03:19 UTC, rayandas approved these changes
LGTM

2022-04-29 03:29 UTC, rancher-max approved these changes
No changes made to k3s/rke2 in latest pushes -- still LGTM

2022-04-29 03:30 UTC, merged