[WIP]: June rke2 release
rancher/kontainer-driver-metadata pull request #920
Opened 2022-06-17 22:25 UTC by matttrach

2022-06-28 15:23 UTC, rancher-max requested changes
At minimum we should set `minChannelServerVersion` to 2.6.6-alpha1 for v1.24, but I think we should just remove the 1.24 section entirely for now until rancher has a version out that will support it at all

2022-06-28 22:45 UTC, rancher-max submitted a review, later dismissed

2022-07-05 16:26 UTC, rancher-max approved these changes

2022-07-05 16:55 UTC, galal-hussein approved these changes

2022-07-05 16:55 UTC, merged