July k3s release
rancher/kontainer-driver-metadata pull request #936
Opened 2022-07-15 17:25 UTC by nikolaishields

2022-07-15 17:29 UTC, rancher-max requested changes
Should be `+k3s1` instead of k3s2 for all of these

2022-07-15 17:31 UTC, VestigeJ commented on channels.yaml
> +  - version: v1.22.12-rc1+k3s2
same fix with s1 vs s2 @nikolaishields

2022-07-15 17:32 UTC, VestigeJ commented on channels.yaml
> +  - version: v1.23.9-rc1+k3s2
same fix with s1 vs s2

2022-07-15 17:33 UTC, VestigeJ commented on data/data.json
> +    "version": "v1.22.12-rc1+k3s2"
v1.22.12-rc1+k3s1 ** @nikolaishields

2022-07-15 17:33 UTC, VestigeJ commented on data/data.json
> +    "version": "v1.23.9-rc1+k3s2"
v1.23.9-rc1+k3s1 **

2022-07-15 17:35 UTC, VestigeJ submitted a review, later dismissed
LGTM thank you @nikolaishields

2022-07-15 17:42 UTC, rancher-max submitted a review, later dismissed
LGTM

2022-07-15 18:00 UTC, kinarashah commented
https://github.com/rancher/rancher/issues/38258

2022-07-15 18:16 UTC, brandond approved these changes, later dismissed

2022-08-29 20:23 UTC, nikolaishields commented
August PR facilitates these changes.

2022-08-29 20:23 UTC, closed without merging