[WIP] K3s August 2022 patch
rancher/kontainer-driver-metadata pull request #959
Opened 2022-08-19 17:47 UTC by brooksn

2022-08-19 17:49 UTC, dereknola approved these changes, later dismissed

2022-08-19 17:50 UTC, briandowns approved these changes, later dismissed

2022-08-19 17:52 UTC, rancher-max commented on channels.yaml
> +  - version: v1.21.13-rc1+k3s1
Is this supposed to be v1.21 or should it be v1.22?

2022-08-19 20:19 UTC, rancher-max requested changes

2022-08-19 20:19 UTC, rancher-max commented on channels.yaml
> +  - version: v1.22.13+k3s1
I think this should still include the rc for now for testing

2022-08-22 22:59 UTC, rancher-max submitted a review, later dismissed

2022-08-25 16:37 UTC, rancher-max approved these changes

2022-08-25 20:05 UTC, merged