K3s release September
rancher/kontainer-driver-metadata pull request #972
Opened 2022-09-16 22:21 UTC by matttrach

2022-09-21 15:36 UTC, rancher-max reviewed
Are the minChannelServerVersion's here correct? I'd generally expect v1.22 to have `v2.6.3-alpha1`, v1.23 to have `v2.6.4-alpha1`, and v1.24 to have `v2.6.7-alpha1`.

It looks correct to me for v1.25 but I'm not 100% if it should be v2.7.0 or v2.7.1. It might make sense to wait on including that one at all until Rancher is more setup for 1.25.

2022-09-22 16:40 UTC, rancher-max commented
https://github.com/rancher/rancher/issues/39083

2022-09-22 18:41 UTC, matttrach commented
sorry, I was going off of the default branch name, I can change them.

2022-09-28 17:47 UTC, rancher-max requested changes
will you rebase this on the current dev-v2.7? It looks like it’s missing some things from there.

also… we'll need to update `maxChannelServerVersion` for all of these versions to be `v2.7.99`. And update the default version at the top of channels.yaml.

2022-09-28 19:06 UTC, rancher-max requested changes

2022-09-28 19:06 UTC, rancher-max commented on channels.yaml
> +    latest: v1.22.15+k3s2
`+k3s1` here then should be good to go!

2022-09-28 19:24 UTC, matttrach commented on channels.yaml
> +    latest: v1.22.15+k3s2
done

2022-09-28 19:40 UTC, rancher-max approved these changes
Perfect! LGTM

2022-09-28 20:17 UTC, brandond commented
Do we need to update the maxChannelServerVersion for all the old releases as well? Otherwise they won't be installable on 2.7. Or is that the desired behavior?

2022-09-28 20:26 UTC, rancher-max commented
> Do we need to update the maxChannelServerVersion for all the old releases as well? Otherwise they won't be installable on 2.7. Or is that the desired behavior?

It was confirmed the other day that just the one previous version is okay. Ref: https://github.com/rancher/kontainer-driver-metadata/pull/978#issuecomment-1258710173

2022-09-28 20:55 UTC, brandond approved these changes

2022-09-29 20:36 UTC, merged